name: Linux CI

on:
  workflow_call:

jobs:

  setup-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      examples-matrix: ${{ steps.set-matrix.outputs.examples-matrix }}
    steps:
      - id: set-matrix
        run: |
          cat > matrix.json << 'EOF'
          {
            "alphabet": ["DNA", "Protein"],
            "build_type": ["Debug", "Release"],
            "compiler": ["g++-11", "g++-12", "g++-13"],
            "build_static": ["OFF", "ON"],
            "with_avx": ["OFF", "ON"],
            "include": [
              {"compiler": "g++-11", "cxx": "g++-11", "cc": "gcc-11"},
              {"compiler": "g++-12", "cxx": "g++-12", "cc": "gcc-12"},
              {"compiler": "g++-13", "cxx": "g++-13", "cc": "gcc-13"}
            ],
            "exclude": [
              {"alphabet": "Protein", "compiler": "g++-11"},
              {"alphabet": "Protein", "compiler": "g++-12"},
              {"compiler": "g++-11", "build_static": "ON"},
              {"compiler": "g++-12", "build_static": "ON"},
              {"build_type": "Debug", "build_static": "ON"},
              {"build_type": "Debug", "compiler": "g++-11"},
              {"build_type": "Debug", "compiler": "g++-12"},
              {"with_avx": "OFF", "build_static": "OFF"}
            ]
          }
          EOF
          
          jq '. + {"example_type": ["subdirectory", "ExternalProject"]}' matrix.json > examples-matrix.json
          
          echo "matrix=$(cat matrix.json | jq -c .)" >> $GITHUB_OUTPUT
          echo "examples-matrix=$(cat examples-matrix.json | jq -c .)" >> $GITHUB_OUTPUT

  Build:
    runs-on: ubuntu-22.04
    needs: setup-matrix

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    name: Linux Build (${{ matrix.alphabet }}, ${{ matrix.build_type }}, ${{ matrix.compiler }}${{ matrix.build_static == 'ON' && ', static' || '' }}${{ matrix.with_avx == 'OFF' && ', noAVX' || '' }})

    steps:
    - uses: actions/checkout@v4

    - name: Cache submodules
      uses: actions/cache@v3
      with:
        path: |
          .git/modules
          metagraph/external-libraries
        key: submodules-${{ hashFiles('.gitmodules') }}
        restore-keys: |
          submodules-

    - name: checkout submodules
      run: git submodule update --init --recursive --depth 1

    - name: checkout metagraph-examples
      run: |
        git clone https://github.com/ratschlab/metagraph-examples.git metagraph-examples
        cd metagraph-examples/subdirectory
        rm -rf metagraph
        ln -s "${GITHUB_WORKSPACE}" metagraph

    - name: install dependencies
      uses: ./.github/actions/install-linux-deps
      with:
        compiler: ${{ matrix.compiler }}
        cc: ${{ matrix.cc }}
        cxx: ${{ matrix.cxx }}
        build_static: ${{ matrix.build_static }}
        install_test_deps: 'true'

    - name: configure
      run: |
        mkdir metagraph/build
        cd metagraph/build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DBUILD_STATIC=${{ matrix.build_static }} \
              -DWITH_AVX=${{ matrix.with_avx }} -DWITH_MSSE42=${{ matrix.with_avx }} \
              -DCMAKE_DBG_ALPHABET=${{ matrix.alphabet }} ..

    - name: build metagraph
      run: cd metagraph/build && make -j"$(getconf _NPROCESSORS_ONLN)" metagraph

    - name: build unit tests
      if: matrix.build_static == 'OFF'
      run: cd metagraph/build && make -j"$(getconf _NPROCESSORS_ONLN)" unit_tests

    - name: build other
      run: cd metagraph/build && make -j"$(getconf _NPROCESSORS_ONLN)"

    # for potential release
    - name: rename binary
      if: matrix.with_avx == 'OFF'
      run: mv metagraph/build/metagraph_${{ matrix.alphabet }} metagraph/build/metagraph_${{ matrix.alphabet }}_noAVX

    - name: upload static binary
      if: ${{ matrix.build_static == 'ON' && matrix.compiler == 'g++-13' }}
      uses: actions/upload-artifact@v4
      with:
        name: metagraph_${{ matrix.alphabet }}${{ matrix.with_avx == 'OFF' && '_noAVX' || '' }}_linux_x86
        path: metagraph/build/metagraph_${{ matrix.alphabet }}${{ matrix.with_avx == 'OFF' && '_noAVX' || '' }}

    # Upload build artifacts for testing
    - name: upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-linux-${{ matrix.alphabet }}-${{ matrix.build_type }}-${{ matrix.compiler }}-${{ matrix.with_avx }}-${{ matrix.build_static }}
        path: |
          metagraph/build/metagraph_${{ matrix.alphabet }}${{ matrix.with_avx == 'OFF' && '_noAVX' || '' }}
          metagraph/build/integration_tests
          metagraph/build/test_venv/
        include-hidden-files: true
        retention-days: 1

    - name: upload unit tests
      if: matrix.build_static == 'OFF'
      uses: actions/upload-artifact@v4
      with:
        name: unit-tests-linux-${{ matrix.alphabet }}-${{ matrix.build_type }}-${{ matrix.compiler }}-${{ matrix.with_avx }}-${{ matrix.build_static }}
        path: metagraph/build/unit_tests
        retention-days: 1


  UnitTests:
    runs-on: ubuntu-22.04
    needs: [setup-matrix, Build]

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    name: Linux Unit Tests (${{ matrix.alphabet }}, ${{ matrix.build_type }}, ${{ matrix.compiler }}${{ matrix.build_static == 'ON' && ', static' || '' }}${{ matrix.with_avx == 'OFF' && ', noAVX' || '' }})

    steps:
    - uses: actions/checkout@v4
      if: matrix.build_static == 'OFF'
      with:
        fetch-depth: 1

    - name: install dependencies
      if: matrix.build_static == 'OFF'
      uses: ./.github/actions/install-linux-deps
      with:
        compiler: ${{ matrix.compiler }}
        cc: ${{ matrix.cc }}
        cxx: ${{ matrix.cxx }}
        build_static: ${{ matrix.build_static }}

    - name: download unit tests
      if: matrix.build_static == 'OFF'
      uses: actions/download-artifact@v4
      with:
        name: unit-tests-linux-${{ matrix.alphabet }}-${{ matrix.build_type }}-${{ matrix.compiler }}-${{ matrix.with_avx }}-${{ matrix.build_static }}
        path: metagraph/build

    - name: run unit tests
      if: matrix.build_static == 'OFF'
      run: |
        export LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
        cd metagraph/build && chmod +x unit_tests && ./unit_tests


  IntegrationTests:
    runs-on: ubuntu-22.04
    needs: [setup-matrix, Build]

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    name: Linux Integration Tests (${{ matrix.alphabet }}, ${{ matrix.build_type }}, ${{ matrix.compiler }}${{ matrix.build_static == 'ON' && ', static' || '' }}${{ matrix.with_avx == 'OFF' && ', noAVX' || '' }})

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: install dependencies
      uses: ./.github/actions/install-linux-deps
      with:
        compiler: ${{ matrix.compiler }}
        cc: ${{ matrix.cc }}
        cxx: ${{ matrix.cxx }}
        build_static: ${{ matrix.build_static }}
        install_test_deps: 'true'

    - name: download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-linux-${{ matrix.alphabet }}-${{ matrix.build_type }}-${{ matrix.compiler }}-${{ matrix.with_avx }}-${{ matrix.build_static }}
        path: metagraph/build

    - name: recreate metagraph symlink
      run: |
        cd metagraph/build
        chmod +x metagraph_${{ matrix.alphabet }}${{ matrix.with_avx == 'OFF' && '_noAVX' || '' }}
        ln -sf metagraph_${{ matrix.alphabet }}${{ matrix.with_avx == 'OFF' && '_noAVX' || '' }} metagraph

    - name: run integration tests
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 1000
        max_attempts: 5
        retry_on: error
        command: |
          export LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
          cd metagraph/build
          chmod +x test_venv/bin/python
          ./test_venv/bin/python ../integration_tests/main.py


  Examples:
    runs-on: ubuntu-22.04
    needs: setup-matrix

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.examples-matrix) }}

    name: Linux ${{ matrix.example_type }} (${{ matrix.alphabet }}, ${{ matrix.build_type }}, ${{ matrix.compiler }}${{ matrix.build_static == 'ON' && ', static' || '' }}${{ matrix.with_avx == 'OFF' && ', noAVX' || '' }})

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Cache submodules
      if: matrix.example_type == 'subdirectory'
      uses: actions/cache@v3
      with:
        path: |
          .git/modules
          metagraph/external-libraries
        key: submodules-${{ hashFiles('.gitmodules') }}
        restore-keys: |
          submodules-

    - name: checkout submodules
      if: matrix.example_type == 'subdirectory'
      run: git submodule update --init --recursive --depth 1

    - name: checkout metagraph-examples
      run: git clone https://github.com/ratschlab/metagraph-examples.git metagraph-examples

    - name: setup metagraph symlink for subdirectory
      if: matrix.example_type == 'subdirectory'
      run: |
        cd metagraph-examples/subdirectory
        rm -rf metagraph
        ln -s "${GITHUB_WORKSPACE}" metagraph

    - name: install dependencies
      uses: ./.github/actions/install-linux-deps
      with:
        compiler: ${{ matrix.compiler }}
        cc: ${{ matrix.cc }}
        cxx: ${{ matrix.cxx }}
        build_static: ${{ matrix.build_static }}

    - name: configure example
      run: |
        cd metagraph-examples/${{ matrix.example_type }}
        mkdir build && cd build
        if [ "${{ matrix.example_type }}" = "subdirectory" ]; then
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DBUILD_STATIC=${{ matrix.build_static }} \
                -DWITH_AVX=${{ matrix.with_avx }} -DWITH_MSSE42=${{ matrix.with_avx }} \
                -DCMAKE_DBG_ALPHABET=${{ matrix.alphabet }} ..
        else
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DMETAGRAPH_GIT_TAG=${{ github.event.pull_request.head.sha || github.sha }} \
                -DBUILD_STATIC=${{ matrix.build_static }} \
                -DWITH_AVX=${{ matrix.with_avx }} -DWITH_MSSE42=${{ matrix.with_avx }} \
                -DCMAKE_DBG_ALPHABET=${{ matrix.alphabet }} ..
        fi

    - name: build example
      run: cd metagraph-examples/${{ matrix.example_type }}/build && make -j"$(getconf _NPROCESSORS_ONLN)"

    - name: run example
      run: |
        cd metagraph-examples/${{ matrix.example_type }}/build
        make run_example
