name: macOS CI

on:
  workflow_call:

jobs:

  setup-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      examples-matrix: ${{ steps.set-matrix.outputs.examples-matrix }}
    steps:
      - id: set-matrix
        run: |
          cat > matrix.json << 'EOF'
          {
            "include": [
              {"alphabet": "DNA", "build_type": "Release", "platform": "macos-latest", "target_arch": "arm64"},
              {"alphabet": "DNA", "build_type": "Release", "platform": "macos-15-intel", "target_arch": "x86_64"},
              {"alphabet": "DNA", "build_type": "Release", "platform": "macos-latest", "target_arch": "x86_64"},
              {"alphabet": "DNA", "build_type": "Debug", "platform": "macos-latest", "target_arch": "arm64"}
            ]
          }
          EOF
          
          jq '{include: ([.include[] as $base | 
                ("subdirectory", "ExternalProject") as $type | 
                $base + {example_type: $type}])}' matrix.json > examples-matrix.json
          
          echo "matrix=$(cat matrix.json | jq -c .)" >> $GITHUB_OUTPUT
          echo "examples-matrix=$(cat examples-matrix.json | jq -c .)" >> $GITHUB_OUTPUT

  Build:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    runs-on: ${{ matrix.platform }}
    name: macOS Build (${{ matrix.alphabet }}, ${{ matrix.build_type }}, ${{ matrix.target_arch }})

    defaults:
      run:
        shell: arch -${{ matrix.target_arch }} /bin/bash -eo pipefail {0}

    steps:
    - uses: actions/checkout@v1

    - name: checkout submodules
      run: git submodule update --init --recursive

    - name: checkout metagraph-examples
      run: |
        git clone https://github.com/ratschlab/metagraph-examples.git metagraph-examples
        cd metagraph-examples/subdirectory
        rm -rf metagraph
        ln -s "${GITHUB_WORKSPACE}" metagraph

    - name: install dependencies
      uses: ./.github/actions/install-macos-deps
      with:
        install_test_deps: 'true'
        target_arch: ${{ matrix.target_arch }}

    - name: configure
      run: |
        mkdir metagraph/build
        cd metagraph/build

        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_DBG_ALPHABET=${{ matrix.alphabet }} \
              ..

    - name: build metagraph
      run: cd metagraph/build && make -j"$(getconf _NPROCESSORS_ONLN)" metagraph

    - name: build unit tests
      run: cd metagraph/build && make -j"$(getconf _NPROCESSORS_ONLN)" unit_tests

    - name: build other
      run: cd metagraph/build && make -j"$(getconf _NPROCESSORS_ONLN)"

    - name: upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-macos-${{ matrix.alphabet }}-${{ matrix.build_type }}-${{ matrix.platform }}-${{ matrix.target_arch }}
        path: |
          metagraph/build/metagraph_${{ matrix.alphabet }}
          metagraph/build/unit_tests
          metagraph/build/integration_tests
          metagraph/build/test_venv/
        retention-days: 1


  UnitTests:
    needs: [setup-matrix, Build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    runs-on: ${{ matrix.platform }}
    name: macOS Unit Tests (${{ matrix.alphabet }}, ${{ matrix.build_type }}, ${{ matrix.target_arch }})

    defaults:
      run:
        shell: arch -${{ matrix.target_arch }} /bin/bash -eo pipefail {0}

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: ./.github/actions/install-macos-deps
      with:
        target_arch: ${{ matrix.target_arch }}

    - name: download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-macos-${{ matrix.alphabet }}-${{ matrix.build_type }}-${{ matrix.platform }}-${{ matrix.target_arch }}
        path: metagraph/build

    - name: run unit tests
      run: cd metagraph/build && chmod +x unit_tests && ./unit_tests


  IntegrationTests:
    needs: [setup-matrix, Build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    runs-on: ${{ matrix.platform }}
    name: macOS Integration Tests (${{ matrix.alphabet }}, ${{ matrix.build_type }}, ${{ matrix.target_arch }})

    defaults:
      run:
        shell: arch -${{ matrix.target_arch }} /bin/bash -eo pipefail {0}

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: ./.github/actions/install-macos-deps
      with:
        install_test_deps: 'true'
        target_arch: ${{ matrix.target_arch }}

    - name: download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-macos-${{ matrix.alphabet }}-${{ matrix.build_type }}-${{ matrix.platform }}-${{ matrix.target_arch }}
        path: metagraph/build

    - name: recreate metagraph symlink
      run: |
        cd metagraph/build
        chmod +x metagraph_${{ matrix.alphabet }}
        ln -sf metagraph_${{ matrix.alphabet }} metagraph

    - name: run integration tests
      run: |
        cd metagraph/build
        chmod +x test_venv/bin/python
        ./test_venv/bin/python ../integration_tests/main.py

    - name: check metagraph workflows
      run: |
        export PATH="$(pwd)/metagraph/build/:$PATH"
        metagraph --help
        # Install python dependencies
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r metagraph/workflows/requirements.txt
        # Test metagraph-workflows pytest
        cd metagraph/workflows
        pytest


  Examples:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.examples-matrix) }}

    runs-on: ${{ matrix.platform }}
    name: macOS ${{ matrix.example_type }} (${{ matrix.alphabet }}, ${{ matrix.build_type }}, ${{ matrix.target_arch }})

    defaults:
      run:
        shell: arch -${{ matrix.target_arch }} /bin/bash -eo pipefail {0}

    steps:
    - uses: actions/checkout@v1

    - name: checkout submodules
      if: matrix.example_type == 'subdirectory'
      run: git submodule update --init --recursive

    - name: checkout metagraph-examples
      run: git clone https://github.com/ratschlab/metagraph-examples.git metagraph-examples

    - name: setup metagraph symlink for subdirectory
      if: matrix.example_type == 'subdirectory'
      run: |
        cd metagraph-examples/subdirectory
        rm -rf metagraph
        ln -s "${GITHUB_WORKSPACE}" metagraph

    - name: install dependencies
      uses: ./.github/actions/install-macos-deps
      with:
        target_arch: ${{ matrix.target_arch }}

    - name: configure example
      run: |
        cd metagraph-examples/${{ matrix.example_type }}
        mkdir build && cd build
        if [ "${{ matrix.example_type }}" = "subdirectory" ]; then
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_DBG_ALPHABET=${{ matrix.alphabet }} ..
        else
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DMETAGRAPH_GIT_TAG=${{ github.event.pull_request.head.sha || github.sha }} \
                -DCMAKE_DBG_ALPHABET=${{ matrix.alphabet }} ..
        fi

    - name: build example
      run: cd metagraph-examples/${{ matrix.example_type }}/build && make -j"$(getconf _NPROCESSORS_ONLN)"

    - name: run example
      run: |
        cd metagraph-examples/${{ matrix.example_type }}/build
        make run_example
